#!/usr/bin/env python3
"""build_tokens.py — emit tokens.py + tokens.css from tokens.json (W3C DTCG).

One palette source, two targets: Python embed ints for the bots and CSS custom
properties for the HTML→PNG cards (Phase 3), so an embed's side-stripe and a
card's alert strip can never drift. The outputs are committed; regenerate after
editing tokens.json:

    python3 ops/discokit/build_tokens.py

stdlib-only, deterministic (dict order follows tokens.json), no timestamps —
a re-run with an unchanged tokens.json is a no-op diff.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
GENERATED = "GENERATED by build_tokens.py from tokens.json — edit tokens.json, not this file."


def emit_py(tokens: dict) -> str:
    lines = [
        f'"""discokit.tokens — the ONE status palette.\n\n{GENERATED}\n',
        "Six semantic states, each a single (colour, glyph, label), plus the accent",
        "hues for embeds that aren't a health state. See tokens.json for the palette",
        'rationale (Primer dark-mode, colourblind-safe glyph+label).\n"""\n',
        "from __future__ import annotations\n",
        "from dataclasses import dataclass\n\n",
        "@dataclass(frozen=True)",
        "class Status:",
        "    key: str",
        "    color: int   # Discord embed colour (int form of the hex)",
        "    glyph: str   # shape-distinct marker; meaning survives colourblindness",
        "    dot: str     # emoji-circle variant for chip rows (never inside code blocks)",
        "    label: str\n\n",
    ]
    statuses = {k: v for k, v in tokens["status"].items() if not k.startswith("$")}
    width = max(len(k) for k in statuses)
    for key, t in statuses.items():
        color = t["color"]["$value"].lstrip("#")
        lines.append(
            f'{key.upper().ljust(width)} = Status("{key}", 0x{color}, '
            f'"{t["glyph"]["$value"]}", "{t["dot"]["$value"]}", "{t["label"]["$value"]}")'
        )
    names = ", ".join(k.upper() for k in statuses)
    lines += [
        "",
        f"ALL = ({names})",
        "BY_KEY = {s.key: s for s in ALL}",
        "",
    ]
    accents = {k: v for k, v in tokens["accent"].items() if not k.startswith("$")}
    awidth = max(len(k) for k in accents)
    lines.append("# Accent hues — identity colours, not statuses (see tokens.json).")
    for key, t in accents.items():
        lines.append(f'{key.upper().ljust(awidth)} = 0x{t["$value"].lstrip("#")}')
    lines += [
        "",
        "",
        "def up_down(is_up: bool) -> Status:",
        '    """Per-item marker: operational when up, critical when down."""',
        "    return OPERATIONAL if is_up else CRITICAL",
        "",
    ]
    return "\n".join(lines)


def emit_css(tokens: dict) -> str:
    lines = [f"/* discokit tokens — {GENERATED} */", ":root {"]
    for key, t in tokens["status"].items():
        if key.startswith("$"):
            continue
        lines.append(f"  --status-{key}: {t['color']['$value'].lower()};")
    for key, t in tokens["accent"].items():
        if key.startswith("$"):
            continue
        lines.append(f"  --accent-{key}: {t['$value'].lower()};")
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> None:
    tokens = json.loads((HERE / "tokens.json").read_text())
    (HERE / "tokens.py").write_text(emit_py(tokens))
    (HERE / "tokens.css").write_text(emit_css(tokens))
    print("wrote tokens.py + tokens.css")


if __name__ == "__main__":
    main()
