"""discokit.tokens — the ONE status palette.

GENERATED by build_tokens.py from tokens.json — edit tokens.json, not this file.

Six semantic states, each a single (colour, glyph, label), plus the accent
hues for embeds that aren't a health state. See tokens.json for the palette
rationale (Primer dark-mode, colourblind-safe glyph+label).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Status:
    key: str
    color: int   # Discord embed colour (int form of the hex)
    glyph: str   # shape-distinct marker; meaning survives colourblindness
    label: str


OPERATIONAL = Status("operational", 0x3FB950, "✅", "operational")
INFO        = Status("info", 0x58A6FF, "ℹ️", "info")
DEGRADED    = Status("degraded", 0xD29922, "⚠️", "degraded")
CRITICAL    = Status("critical", 0xF85149, "🔴", "critical")
MAINTENANCE = Status("maintenance", 0xA371F7, "🛠️", "maintenance")
UNKNOWN     = Status("unknown", 0x8B949E, "⚪", "unknown")

ALL = (OPERATIONAL, INFO, DEGRADED, CRITICAL, MAINTENANCE, UNKNOWN)
BY_KEY = {s.key: s for s in ALL}

# Accent hues — identity colours, not statuses (see tokens.json).
BLURPLE = 0x5865F2
ORANGE  = 0xDB6D28
PURPLE  = 0x8957E5


def up_down(is_up: bool) -> Status:
    """Per-item marker: operational when up, critical when down."""
    return OPERATIONAL if is_up else CRITICAL
