#!/usr/bin/env python3
"""uptime.py — render the fleet-infrastructure uptime table from InfluxDB.

The "live uptime data" behind the dev-wiki Infrastructure section
(docs/infrastructure.md). Reads the metrics we ALREADY collect — Telegraf's
host/container inputs + the redis input on the Valkey bus + the http_response
service probes, all in the `system` bucket — and rewrites the markdown table
between the

    <!-- UPTIME:START --> … <!-- UPTIME:END -->

markers in the target page. The doc keeps the markers (the stub); this fills them.
Run on a cadence (a live-loop Job / cron) so the wiki shows current values on its
next build. No new dependency — influxdb-client is already in the base image.

    python3 ops/uptime.py --page docs/infrastructure.md          # rewrite in place
    python3 ops/uptime.py --print                                # just print the block
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

START = "<!-- UPTIME:START -->"
END = "<!-- UPTIME:END -->"

# The synthetic HTTP probes Telegraf runs (inputs.http_response) → friendly names.
SERVICES = {
    "http://localhost:8086/health": "InfluxDB",
    "http://localhost:8077/": "dev-status",
    "http://localhost:3001/api/health": "ask-dash",
}


def _humanize(seconds: float) -> str:
    s = int(seconds)
    d, s = divmod(s, 86400)
    h, s = divmod(s, 3600)
    m, _ = divmod(s, 60)
    if d:
        return f"{d}d {h}h"
    if h:
        return f"{h}h {m}m"
    return f"{m}m"


def _dot(up: bool) -> str:
    return "🟢" if up else "🔴"


def gather(url: str, token: str, org: str) -> dict:
    """Query the system bucket for valkey uptime, service uptime%, container states."""
    from influxdb_client import InfluxDBClient

    out: dict = {"valkey": None, "services": {}}
    with InfluxDBClient(url=url, token=token, org=org) as client:
        q = client.query_api()

        # Valkey (the bus) — current uptime in seconds (telegraf redis input).
        for t in q.query(
            'from(bucket:"system") |> range(start:-10m)'
            ' |> filter(fn:(r)=> r._measurement=="redis" and r._field=="uptime")'
            ' |> last()', org=org):
            for r in t.records:
                out["valkey"] = float(r.get_value())

        # Service probes (http_response) — 24h success ratio per endpoint.
        for t in q.query(
            'from(bucket:"system") |> range(start:-24h)'
            ' |> filter(fn:(r)=> r._measurement=="http_response" and r._field=="result_code")'
            ' |> map(fn:(r)=>({server:r.server, _value: if r._value==0 then 1.0 else 0.0}))'
            ' |> keep(columns:["server","_value"])'
            ' |> group(columns:["server"]) |> mean()', org=org):
            for r in t.records:
                out["services"].setdefault(r.values.get("server", "?"), {})["pct"] = \
                    100.0 * (r.get_value() or 0.0)
        # Current state — the latest probe per endpoint (0 == up).
        for t in q.query(
            'from(bucket:"system") |> range(start:-10m)'
            ' |> filter(fn:(r)=> r._measurement=="http_response" and r._field=="result_code")'
            ' |> group(columns:["server"]) |> last()', org=org):
            for r in t.records:
                out["services"].setdefault(r.values.get("server", "?"), {})["up"] = \
                    (r.get_value() == 0)
    return out


def render(data: dict) -> str:
    lines = [
        START,
        "",
        "| Component | Status | Uptime / availability |",
        "| --- | --- | --- |",
    ]
    v = data.get("valkey")
    lines.append(
        f"| **Valkey** (message bus) | {_dot(v is not None)} {'up' if v is not None else 'unknown'}"
        f" | {_humanize(v) if v is not None else '—'} |"
    )
    for server, name in SERVICES.items():
        s = data["services"].get(server)
        if not s or "pct" not in s:
            lines.append(f"| **{name}** | ⚪ no data | — |")
            continue
        up = s.get("up", s["pct"] > 50)
        lines.append(f"| **{name}** | {_dot(up)} {'up' if up else 'down'} | {s['pct']:.1f}% (24h) |")
    lines += [
        "",
        "_Source: Telegraf → InfluxDB `system` bucket (`redis`, `http_response`). "
        "Regenerated by `ops/uptime.py`; the wiki shows the value at its last build._",
        "",
        END,
    ]
    return "\n".join(lines)


def inject(page: Path, block: str) -> bool:
    text = page.read_text()
    if START not in text or END not in text:
        print(f"[uptime] markers not found in {page}", file=sys.stderr)
        return False
    head = text.split(START)[0]
    tail = text.split(END, 1)[1]
    page.write_text(head + block + tail)
    return True


def main() -> None:
    ap = argparse.ArgumentParser(description="render the fleet uptime table from InfluxDB")
    ap.add_argument("--page", default="docs/infrastructure.md", help="page to rewrite (markers)")
    ap.add_argument("--print", action="store_true", dest="just_print", help="print the block, don't write")
    args = ap.parse_args()

    url = os.environ.get("INFLUXDB_URL", "http://localhost:8086")
    token = os.environ.get("INFLUXDB_TOKEN", "")
    org = os.environ.get("INFLUXDB_ORG", "home")
    if not token:
        print("[uptime] INFLUXDB_TOKEN not set", file=sys.stderr)
        sys.exit(1)

    block = render(gather(url, token, org))
    if args.just_print:
        print(block)
        return
    page = Path(args.page)
    if not page.is_absolute():
        page = Path(__file__).resolve().parent.parent / args.page
    print("[uptime] rewrote" if inject(page, block) else "[uptime] no change", page)


if __name__ == "__main__":
    main()
